export const PROJECT_STATUS = {
  APPLICATION_REVIEW: "APPLICATION_REVIEW",
  WORKING: "WORKING",
  SUBMISSION_REVIEW: "SUBMISSION_REVIEW",
  COMPLETE: "COMPLETE",
};

export type ProjectStatus = keyof typeof PROJECT_STATUS;
