export const PROJECT_STATUS = {
  APPLY: "APPLY",
  APPLICATION_REVIEW: "APPLICATION_REVIEW",
  WORKING: "WORKING",
  SUBMISSION_REVIEW: "SUBMISSION_REVIEW",
  MINTABLE: "MINEABLE",
  MINTED: "MINTED",
};

export type ProjectStatus = keyof typeof PROJECT_STATUS;
